### ISSUE TITLE
Spelling mistakes at the end of the SQLs

### ISSUE THREAD

**Issue by chenhongen** [tristaZero/federatedSQL#3]
**Describe the bug**
hi~
`INSERT INTO t_order_item_2 SET order_id = 1, user_id = 1, order_item_id = 1;`
 t_order_item_**2** should be t_order_item_**1**

**Comment by tristaZero** [comment]
@chenhongen Hi, I can not imagine this repo will be noticed one day. Thanks, but could you explain that where this bug locates?

**Comment by chenhongen** [comment]
hah~ In the README.md line 84, the table name spell wrong with "t_order_item_2",because of the demo only have two tables, t_order_item_0   t_order_item_1

**Comment by tristaZero** [comment]
Fixed, thanks.
